---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - sentry.io.x42r
  resources:
  - sentryprojects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sentry.io.x42r
  resources:
  - sentryprojects/finalizers
  verbs:
  - update
- apiGroups:
  - sentry.io.x42r
  resources:
  - sentryprojects/status
  verbs:
  - get
  - patch
  - update
